In [8]:
import numpy as np
import pandas as pd
from numpy import random

In [9]:
# task 1
ali = list(range(12,24))

In [10]:
ali

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [11]:
a = np.array(ali)

In [12]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [13]:
#task 2 
a1 = np.arange(12,24).reshape(2,6)

In [14]:
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
a2 = np.arange(12,24).reshape(3,4)

In [16]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
a3 = np.arange(12,24).reshape(4,3)

In [18]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [19]:
a4 =  np.arange(12,24).reshape(6,2)

In [20]:
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [21]:
a5 = a.reshape(2,3,2)

In [22]:
a5

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [23]:
# task 3

In [24]:
b1 = a.reshape(2,-1)

In [25]:
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
b2 = a.reshape(6,-1)

In [27]:
b2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [28]:
b3 = a.reshape(3,-1)

In [29]:
b3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
b4 = a.reshape(-1,2)

In [31]:
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [32]:
b5 = a.reshape(-1,6)

In [33]:
b5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
#task 4
# NO


In [35]:
# task 5
#np.array([random.normalvariate(0, 1.0) for i in range(10)])

In [36]:
r = random.normal(0, 1.0, (3, 4))

In [37]:
r

array([[-1.63261012e+00,  1.61879187e+00,  1.11292173e+00,
        -1.48089503e+00],
       [ 6.99062053e-01,  3.41475708e-01,  7.20441517e-01,
        -4.49705964e-01],
       [-1.48318421e+00, -3.98162492e-02,  1.15133210e-03,
         5.78459254e-01]])

In [38]:
r.reshape(1,-1)

array([[-1.63261012e+00,  1.61879187e+00,  1.11292173e+00,
        -1.48089503e+00,  6.99062053e-01,  3.41475708e-01,
         7.20441517e-01, -4.49705964e-01, -1.48318421e+00,
        -3.98162492e-02,  1.15133210e-03,  5.78459254e-01]])

In [39]:
r.reshape(1,12)

array([[-1.63261012e+00,  1.61879187e+00,  1.11292173e+00,
        -1.48089503e+00,  6.99062053e-01,  3.41475708e-01,
         7.20441517e-01, -4.49705964e-01, -1.48318421e+00,
        -3.98162492e-02,  1.15133210e-03,  5.78459254e-01]])

In [40]:
r.reshape(-1)

array([-1.63261012e+00,  1.61879187e+00,  1.11292173e+00, -1.48089503e+00,
        6.99062053e-01,  3.41475708e-01,  7.20441517e-01, -4.49705964e-01,
       -1.48318421e+00, -3.98162492e-02,  1.15133210e-03,  5.78459254e-01])

In [41]:
#task 6
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
# В чем разница между массивами a и b?

In [42]:
adesce = np.arange(20,0,-2)

In [43]:
adesce

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [44]:
bdesce = np.arange(20,1,-2)

In [45]:
bdesce

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [46]:
bdesce.reshape(1,-1)

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [47]:
# последний двумерный

In [48]:
#task 7
#7. Вертикально соединить массивы a и b. a — двумерный массив из нулей, число строк которого больше 1 и на 1 меньше
#, чем число строк двумерного массива b, состоящего из единиц.
#Итоговый массив v должен иметь атрибут size, равный 10.

In [49]:
atmp = [0]*4

In [50]:
atmp

[0, 0, 0, 0]

In [51]:
anp = np.array(atmp)

In [52]:
anp

array([0, 0, 0, 0])

In [53]:
bre = anp.reshape(2,2)

In [54]:
bre

array([[0, 0],
       [0, 0]])

In [55]:
a1tmp = [1]*6

In [56]:
bre.size

4

In [57]:
anp1 = np.array(a1tmp)

In [58]:
bre1 = anp1.reshape(3,2)

In [59]:
bre1

array([[1, 1],
       [1, 1],
       [1, 1]])

In [60]:
res7  = np.vstack((bre, bre1))


In [63]:
#res7
res7.size

10

In [ ]:
#task 8
#Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
#Поменять форму этого массива, чтобы #получилась матрица A (двумерный массив Numpy),
#состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования #матрицы A.
#Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
#Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [70]:
anp8 = np.arange(12)

In [71]:
anp8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
anp8re = anp8.reshape(4,3)

In [82]:
anp8re

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
anp8tr = np.transpose(anp8re)

In [80]:
anp8tr

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [84]:
b8 = np.dot(anp8re, anp8tr)

In [85]:
b8

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [86]:
#task 9
# Инициализируйте генератор случайных числе с помощью объекта seed
# , равного 42. Создайте одномерный массив c, 
# составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно.
# Поменяйте его форму так, чтобы получилась квадратная матрица C.
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C,
# умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [133]:
np.random.seed(42)

In [134]:
c9 = np.random.randint(0,16,(1,16))

In [135]:
c9

array([[ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4]])

In [136]:
c9.resize(4,4)

In [137]:
for index, val in enumerate(b8):
    print(f"val - {val} , index - {index }")

val - [ 5 14 23 32] , index - 0
val - [ 14  50  86 122] , index - 1
val - [ 23  86 149 212] , index - 2
val - [ 32 122 212 302] , index - 3


In [138]:
c9=c9*10

In [139]:
c9

array([[ 60,  30, 120, 140],
       [100,  70, 120,  40],
       [ 60,  90,  20,  60],
       [100, 100,  70,  40]])

In [164]:
for index, val in enumerate(b8):
    print(f"val - {val} c9[index] {c9[index]} ")
    c9[index] = val+c9[index]
    print(f"c9[index] - {c9[index]}")

val - [ 5 14 23 32] c9[index] [ 60  30 120 140] 
c9[index] - [ 65  44 143 172]
val - [ 14  50  86 122] c9[index] [100  70 120  40] 
c9[index] - [114 120 206 162]
val - [ 23  86 149 212] c9[index] [60 90 20 60] 
c9[index] - [ 83 176 169 272]
val - [ 32 122 212 302] c9[index] [100 100  70  40] 
c9[index] - [132 222 282 342]


In [167]:
c9

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [169]:
#определитель матрицы
d = np.linalg.det(c9)


In [173]:
print(f"определитель матрицы {d}")

определитель матрицы -28511999.999999944


In [174]:
r = np.linalg.matrix_rank(c9)
print(f" ранг матрицы {r}")

 ранг матрицы 4


In [175]:
d_inv = np.linalg.inv(c9)

In [176]:
d_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [177]:
#task 10
# 10. Приравняйте к нулю отрицательные числа в матрице D_inv, 
# а положительные — к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C — в качестве источников данных
# , получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1
# , должны быть равны соответствующему элементу матрицы B, а элементы матрицы E
# , для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [180]:
ind1 = np.where(d_inv < 0)

In [181]:
ind1

(array([0, 1, 1, 1, 2, 2, 2, 3, 3], dtype=int64),
 array([3, 0, 1, 2, 0, 1, 2, 1, 3], dtype=int64))

In [186]:
for index, val in enumerate(d_inv):
    print(f"val - {val} c9[index] {c9[index]} ")
    for indexIn, valIn in enumerate(val):
        print(f"val - {valIn} c9[index] {c9[indexIn]} ")
        if valIn < 0:
            val[indexIn] = 0
        else:
            if valIn > 0:
                val[indexIn] = 1

val - [ 0.00935396  0.04486532  0.05897517 -0.07286055] c9[index] [ 65  44 143 172] 
val - 0.009353956228956227 c9[index] [ 65  44 143 172] 
val - 0.04486531986531985 c9[index] [114 120 206 162] 
val - 0.058975168350168326 c9[index] [ 83 176 169 272] 
val - -0.07286054994388325 c9[index] [132 222 282 342] 
val - [-0.01503577 -0.00122896 -0.00192971  0.00967873] c9[index] [114 120 206 162] 
val - -0.015035774410774411 c9[index] [ 65  44 143 172] 
val - -0.0012289562289562262 c9[index] [114 120 206 162] 
val - -0.0019297138047137971 c9[index] [ 83 176 169 272] 
val - 0.009678731762065093 c9[index] [132 222 282 342] 
val - [-0.00356692 -0.01782828 -0.04152146  0.04326178] c9[index] [ 83 176 169 272] 
val - -0.0035669191919191876 c9[index] [ 65  44 143 172] 
val - -0.01782828282828283 c9[index] [114 120 206 162] 
val - -0.04152146464646464 c9[index] [ 83 176 169 272] 
val - 0.043261784511784494 c9[index] [132 222 282 342] 
val - [ 0.00909091 -0.00181818  0.01272727 -0.01090909] c9[index] [

In [187]:
d_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [190]:
d1index = np.where(d_inv==1)

In [204]:
d1index

(array([0, 0, 0, 1, 2, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 3, 0, 2], dtype=int64))

In [192]:
d1res = d_inv[d1index]

In [193]:
d1res

array([1., 1., 1., 1., 1., 1., 1.])

In [201]:
d0index = np.where(d_inv==0)

In [202]:
d0res = d_inv[d0index]

In [203]:
d0res

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])